version: 2

sources:
  - name: raw
    schema: bronze
    tables:
      - name: raw_311_complaints

models:
  - name: silver_complaints
    columns:
      - name: unique_key
        tests: [not_null, unique]
  - name: gold_fct_complaints
    columns:
      - name: complaint_created_date
        tests: [not_null]
