{{ config(materialized='table', partition_by={"field": "complaint_date", "data_type": "date"}, cluster_by=["borough", "law_category", "offense_description"]) }}

select
  complaint_id,
  source_dataset,
  complaint_start_ts,
  complaint_end_ts,
  reported_ts,
  complaint_date,
  complaint_year,
  complaint_month,
  complaint_day_of_week,
  complaint_hour,
  precinct,
  offense_code,
  offense_description,
  internal_classification_code,
  internal_classification_description,
  attempt_completed,
  law_category,
  borough,
  occurrence_location,
  premise_type,
  jurisdiction,
  park_name,
  housing_development,
  housing_psa,
  x_coord,
  y_coord,
  latitude,
  longitude,
  patrol_borough,
  station_name,
  transit_district,
  has_valid_nyc_coordinates
from {{ ref('silver_crime_events') }}
